#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git branch --show-current)" ;
echo branch: $branch ;

if [ "$branch" = "main" ] || [ "$branch" = "release" ] || [ "$branch" = "develop" ]; 
then
    echo run script ;
    yarn build ; 
else 
    echo not on branch main, release nor develop ;
    echo skip script ;
fi
